import java.io.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.*;
import java.io.RandomAccessFile;
import java.io.BufferedReader;
public class HighScores extends JFrame
{
    static String currentUser;
    private JMenuBar menuBar;
    private JTextField User;
    private JTextField Score;
    private JButton exit;
    private JTextField Trapped,TrappedUser,TrappedScore;
    private JTextField PinBall,PinBallUser,PinBallScore;
    private JTextField Brick,BrickUser,BrickScore;
    private JTextField Frogger,FroggerUser,FroggerScore;
    private JTextField Troll,TrollUser,TrollScore;
    private JTextField Slot,SlotUser,SlotScore;
    private JTextField BS,BSUser,BSScore;
    private JTextField Snake,SnakeUser,SnakeScore;
    private JTextField Space,SpaceUser,SpaceScore;
    private JTextField t,t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11;
    public HighScores() throws IOException
    {
        setTitle("High Scores");
        setSize(500,400);
        JPanel contentPane = new JPanel(null);
        contentPane.setPreferredSize(new Dimension(500,700));
        contentPane.setBackground(new Color(8,8,252));
        ReadHS temp = new ReadHS();
        String tScore = temp.getTrappedS();
        String tUser = temp.getTrappedU();
        String bScore = temp.getBrickS();
        String bUser = temp.getBrickU();
        String pScore = temp.getPinBallS();
        String pUser = temp.getPinBallU();
        String fUser = temp.getFroggerU();
        String fScore = temp.getFroggerS();
        String TrollU = temp.getTrollU();
        String TrollS = temp.getTrollS();
        String SlotU = temp.getSlotU();
        String SlotS = temp.getSlotS();
        String BSU = temp.getBSU();
        String BSS = temp.getBSS();
        String SnakeU = temp.getSnakeU();
        String SnakeS = temp.getSnakeS();
        String SpaceU = temp.getSpaceU();
        String SpaceS = temp.getSpaceS();
        User = new JTextField();
        User.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        User.setBounds(175,25,90,35);
        User.setBackground(new Color(8,8,252));
        User.setForeground(new Color(0,0,0));
        User.setEditable(false);
        User.setFont(new Font("sansserif",0,12));
        User.setText("User");
        User.setVisible(true);
        Score = new JTextField();
        Score.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        Score.setBounds(295,25,90,35);
        Score.setBackground(new Color(8,8,252));
        Score.setForeground(new Color(0,0,0));
        Score.setEditable(false);
        Score.setFont(new Font("sansserif",0,12));
        Score.setText("Score");
        Score.setVisible(true);
        Brick = new JTextField();
        Brick.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        Brick.setBounds(45,86,100,35);
        Brick.setBackground(new Color(8,8,252));
        Brick.setForeground(new Color(0,0,0));
        Brick.setEditable(false);
        Brick.setFont(new Font("sansserif",0,12));
        Brick.setText("Brick Breaker");
        Brick.setVisible(true);
        BrickScore = new JTextField();
        BrickScore.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        BrickScore.setBounds(295,86,90,35);
        BrickScore.setBackground(new Color(8,8,252));
        BrickScore.setForeground(new Color(0,0,0));
        BrickScore.setEditable(false);
        BrickScore.setFont(new Font("sansserif",0,12));
        BrickScore.setText(bScore);
        BrickScore.setVisible(true);
        BrickUser = new JTextField();
        BrickUser.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        BrickUser.setBounds(175,86,90,35);
        BrickUser.setBackground(new Color(8,8,252));
        BrickUser.setForeground(new Color(0,0,0));
        BrickUser.setEditable(false);
        BrickUser.setFont(new Font("sansserif",0,12));
        BrickUser.setText(bUser);
        BrickUser.setVisible(true);
        Frogger = new JTextField();
        Frogger.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        Frogger.setBounds(45,269,100,35);
        Frogger.setBackground(new Color(8,8,252));
        Frogger.setForeground(new Color(0,0,0));
        Frogger.setEditable(false);
        Frogger.setFont(new Font("sansserif",0,12));
        Frogger.setText("Frogger");
        Frogger.setVisible(true);
        FroggerScore = new JTextField();
        FroggerScore.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        FroggerScore.setBounds(295,269,90,35);
        FroggerScore.setBackground(new Color(8,8,252));
        FroggerScore.setForeground(new Color(0,0,0));
        FroggerScore.setEditable(false);
        FroggerScore.setFont(new Font("sansserif",0,12));
        FroggerScore.setText(fScore);
        FroggerScore.setVisible(true);
        FroggerUser = new JTextField();
        FroggerUser.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        FroggerUser.setBounds(175,269,90,35);
        FroggerUser.setBackground(new Color(8,8,252));
        FroggerUser.setForeground(new Color(0,0,0));
        FroggerUser.setEditable(false);
        FroggerUser.setFont(new Font("sansserif",0,12));
        FroggerUser.setText(fUser);
        FroggerUser.setVisible(true);
        PinBall = new JTextField();
        PinBall.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        PinBall.setBounds(45,147,100,35);
        PinBall.setBackground(new Color(8,8,252));
        PinBall.setForeground(new Color(0,0,0));
        PinBall.setEditable(false);
        PinBall.setFont(new Font("sansserif",0,12));
        PinBall.setText("Pin Ball");
        PinBall.setVisible(true);
        PinBallScore = new JTextField();
        PinBallScore.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        PinBallScore.setBounds(295,147,90,35);
        PinBallScore.setBackground(new Color(8,8,252));
        PinBallScore.setForeground(new Color(0,0,0));
        PinBallScore.setEditable(false);
        PinBallScore.setFont(new Font("sansserif",0,12));
        PinBallScore.setText(pScore);
        PinBallScore.setVisible(true);
        PinBallUser = new JTextField();
        PinBallUser.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        PinBallUser.setBounds(175,147,90,35);
        PinBallUser.setBackground(new Color(8,8,252));
        PinBallUser.setForeground(new Color(0,0,0));
        PinBallUser.setEditable(false);
        PinBallUser.setFont(new Font("sansserif",0,12));
        PinBallUser.setText(pUser);
        PinBallUser.setVisible(true);
        Trapped = new JTextField();
        Trapped.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        Trapped.setBounds(45,208,100,35);
        Trapped.setBackground(new Color(8,8,252));
        Trapped.setForeground(new Color(0,0,0));
        Trapped.setEditable(false);
        Trapped.setFont(new Font("sansserif",0,12));
        Trapped.setText("Trapped Game");
        Trapped.setVisible(true);
        TrappedScore = new JTextField();
        TrappedScore.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        TrappedScore.setBounds(295,208,90,35);
        TrappedScore.setBackground(new Color(8,8,252));
        TrappedScore.setForeground(new Color(0,0,0));
        TrappedScore.setEditable(false);
        TrappedScore.setFont(new Font("sansserif",0,12));
        TrappedScore.setText(tScore);
        TrappedScore.setVisible(true);
        TrappedUser = new JTextField();
        TrappedUser.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        TrappedUser.setBounds(175,208,90,35);
        TrappedUser.setBackground(new Color(8,8,252));
        TrappedUser.setForeground(new Color(0,0,0));
        TrappedUser.setEditable(false);
        TrappedUser.setFont(new Font("sansserif",0,12));
        TrappedUser.setText(String.valueOf(tUser));
        TrappedUser.setVisible(true);
        Troll = new JTextField();
        Troll.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        Troll.setBounds(45,330,100,35);
        Troll.setBackground(new Color(8,8,252));
        Troll.setForeground(new Color(0,0,0));
        Troll.setEditable(false);
        Troll.setFont(new Font("sansserif",0,12));
        Troll.setText("Troll run");
        Troll.setVisible(true);
        TrollUser = new JTextField();
        TrollUser.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        TrollUser.setBounds(175,330,100,35);
        TrollUser.setBackground(new Color(8,8,252));
        TrollUser.setForeground(new Color(0,0,0));
        TrollUser.setEditable(false);
        TrollUser.setFont(new Font("sansserif",0,12));
        TrollUser.setText(TrollU);
        TrollUser.setVisible(true);
        TrollScore = new JTextField();
        TrollScore.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        TrollScore.setBounds(295,330,100,35);
        TrollScore.setBackground(new Color(8,8,252));
        TrollScore.setForeground(new Color(0,0,0));
        TrollScore.setEditable(false);
        TrollScore.setFont(new Font("sansserif",0,12));
        TrollScore.setText(TrollS);
        TrollScore.setVisible(true);
        Slot = new JTextField();
        Slot.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        Slot.setBounds(45,391,100,35);
        Slot.setBackground(new Color(8,8,252));
        Slot.setForeground(new Color(0,0,0));
        Slot.setEditable(false);
        Slot.setFont(new Font("sansserif",0,12));
        Slot.setText("Slot Machine");
        Slot.setVisible(true);
        SlotUser = new JTextField();
        SlotUser.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        SlotUser.setBounds(175,391,100,35);
        SlotUser.setBackground(new Color(8,8,252));
        SlotUser.setForeground(new Color(0,0,0));
        SlotUser.setEditable(false);
        SlotUser.setFont(new Font("sansserif",0,12));
        SlotUser.setText(SlotU);
        SlotUser.setVisible(true);
        SlotScore = new JTextField();
        SlotScore.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        SlotScore.setBounds(295,391,100,35);
        SlotScore.setBackground(new Color(8,8,252));
        SlotScore.setForeground(new Color(0,0,0));
        SlotScore.setEditable(false);
        SlotScore.setFont(new Font("sansserif",0,12));
        SlotScore.setText(SlotS);
        SlotScore.setVisible(true);
        BS = new JTextField();
        BS.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        BS.setBounds(45,452,100,35);
        BS.setBackground(new Color(8,8,252));
        BS.setForeground(new Color(0,0,0));
        BS.setEditable(false);
        BS.setFont(new Font("sansserif",0,12));
        BS.setText("Bubble Shooter");
        BS.setVisible(true);
        BSUser = new JTextField();
        BSUser.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        BSUser.setBounds(175,452,100,35);
        BSUser.setBackground(new Color(8,8,252));
        BSUser.setForeground(new Color(0,0,0));
        BSUser.setEditable(false);
        BSUser.setFont(new Font("sansserif",0,12));
        BSUser.setText(BSU);
        BSUser.setVisible(true);
        BSScore = new JTextField();
        BSScore.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        BSScore.setBounds(295,452,100,35);
        BSScore.setBackground(new Color(8,8,252));
        BSScore.setForeground(new Color(0,0,0));
        BSScore.setEditable(false);
        BSScore.setFont(new Font("sansserif",0,12));
        BSScore.setText(BSS);
        BSScore.setVisible(true);
        Snake = new JTextField();
        Snake.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        Snake.setBounds(45,513,100,35);
        Snake.setBackground(new Color(8,8,252));
        Snake.setForeground(new Color(0,0,0));
        Snake.setEditable(false);
        Snake.setFont(new Font("sansserif",0,12));
        Snake.setText("Snake");
        Snake.setVisible(true);
        SnakeUser = new JTextField();
        SnakeUser.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        SnakeUser.setBounds(175,513,100,35);
        SnakeUser.setBackground(new Color(8,8,252));
        SnakeUser.setForeground(new Color(0,0,0));
        SnakeUser.setEditable(false);
        SnakeUser.setFont(new Font("sansserif",0,12));
        SnakeUser.setText(SnakeU);
        SnakeUser.setVisible(true);
        SnakeScore = new JTextField();
        SnakeScore.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        SnakeScore.setBounds(295,513,100,35);
        SnakeScore.setBackground(new Color(8,8,252));
        SnakeScore.setForeground(new Color(0,0,0));
        SnakeScore.setEditable(false);
        SnakeScore.setFont(new Font("sansserif",0,12));
        SnakeScore.setText(SnakeS);
        SnakeScore.setVisible(true);
        Space = new JTextField();
        Space.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        Space.setBounds(45,574,100,35);
        Space.setBackground(new Color(8,8,252));
        Space.setForeground(new Color(0,0,0));
        Space.setEditable(false);
        Space.setFont(new Font("sansserif",0,12));
        Space.setText("Space Game");
        Space.setVisible(true);
        SpaceUser = new JTextField();
        SpaceUser.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        SpaceUser.setBounds(175,574,100,35);
        SpaceUser.setBackground(new Color(8,8,252));
        SpaceUser.setForeground(new Color(0,0,0));
        SpaceUser.setEditable(false);
        SpaceUser.setFont(new Font("sansserif",0,12));
        SpaceUser.setText(SpaceU);
        SpaceUser.setVisible(true);
        SpaceScore = new JTextField();
        SpaceScore.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        SpaceScore.setBounds(295,574,100,35);
        SpaceScore.setBackground(new Color(8,8,252));
        SpaceScore.setForeground(new Color(0,0,0));
        SpaceScore.setEditable(false);
        SpaceScore.setFont(new Font("sansserif",0,12));
        SpaceScore.setText(SpaceS);
        SpaceScore.setVisible(true);
        t = new JTextField();
        t.setBounds(160,0,5,621);
        t.setBackground(new Color(255,255,255));
        t.setForeground(new Color(0,0,0));
        t.setEditable(false);
        t.setFont(new Font("sansserif",0,12));
        t.setText("");
        t.setVisible(true);
        t1 = new JTextField();
        t1.setBounds(280,0,5,621);
        t1.setBackground(new Color(255,255,255));
        t1.setForeground(new Color(0,0,0));
        t1.setEditable(false);
        t1.setFont(new Font("sansserif",0,12));
        t1.setText("");
        t1.setVisible(true);
        t2 = new JTextField();
        t2.setBounds(0,190,500,5);
        t2.setBackground(new Color(255,255,255));
        t2.setForeground(new Color(0,0,0));
        t2.setEditable(false);
        t2.setFont(new Font("sansserif",0,12));
        t2.setText("");
        t2.setVisible(true);
        t3 = new JTextField();
        t3.setBounds(0,255,500,5);
        t3.setBackground(new Color(255,255,255));
        t3.setForeground(new Color(0,0,0));
        t3.setEditable(false);
        t3.setFont(new Font("sansserif",0,12));
        t3.setText("");
        t3.setVisible(true);
        t4 = new JTextField();
        t4.setBounds(0,65,500,5);
        t4.setBackground(new Color(255,255,255));
        t4.setForeground(new Color(0,0,0));
        t4.setEditable(false);
        t4.setFont(new Font("sansserif",0,12));
        t4.setText("");
        t4.setVisible(true);
        t5 = new JTextField();
        t5.setBounds(0,125,500,5);
        t5.setBackground(new Color(255,255,255));
        t5.setForeground(new Color(0,0,0));
        t5.setEditable(false);
        t5.setFont(new Font("sansserif",0,12));
        t5.setText("");
        t5.setVisible(true);
        t6 = new JTextField();
        t6.setBounds(0,316,500,5);
        t6.setBackground(new Color(255,255,255));
        t6.setForeground(new Color(0,0,0));
        t6.setEditable(false);
        t6.setFont(new Font("sansserif",0,12));
        t6.setText("");
        t6.setVisible(true);
        t7 = new JTextField();
        t7.setBounds(0,377,500,5);
        t7.setBackground(new Color(255,255,255));
        t7.setForeground(new Color(0,0,0));
        t7.setEditable(false);
        t7.setFont(new Font("sansserif",0,12));
        t7.setText("");
        t7.setVisible(true);
        t8 = new JTextField();
        t8.setBounds(0,438,500,5);
        t8.setBackground(new Color(255,255,255));
        t8.setForeground(new Color(0,0,0));
        t8.setEditable(false);
        t8.setFont(new Font("sansserif",0,12));
        t8.setText("");
        t8.setVisible(true);
        t9 = new JTextField();
        t9.setBounds(0,499,500,5);
        t9.setBackground(new Color(255,255,255));
        t9.setForeground(new Color(0,0,0));
        t9.setEditable(false);
        t9.setFont(new Font("sansserif",0,12));
        t9.setText("");
        t9.setVisible(true);
        t10 = new JTextField();
        t10.setBounds(0,560,500,5);
        t10.setBackground(new Color(255,255,255));
        t10.setForeground(new Color(0,0,0));
        t10.setEditable(false);
        t10.setFont(new Font("sansserif",0,12));
        t10.setText("");
        t10.setVisible(true);
        t11 = new JTextField();
        t11.setBounds(0,621,500,5);
        t11.setBackground(new Color(255,255,255));
        t11.setForeground(new Color(0,0,0));
        t11.setEditable(false);
        t11.setFont(new Font("sansserif",0,12));
        t11.setText("");
        t.setVisible(true);
        exit = new JButton();
        exit.setBounds(175,634,90,35);
        exit.setBackground(new Color(214,217,223));
        exit.setForeground(new Color(0,0,0));
        exit.setEnabled(true);
        exit.setFont(new Font("sansserif",0,12));
        exit.setText("Exit");
        exit.setVisible(true);
        exit.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                exit(evt);
            }
        });
        contentPane.add(t);
        contentPane.add(t1);
        contentPane.add(t2);
        contentPane.add(t3);
        contentPane.add(t4);
        contentPane.add(t5);
        contentPane.add(t6);
        contentPane.add(t7);
        contentPane.add(t8);
        contentPane.add(t9);
        contentPane.add(t10);
        contentPane.add(t11);
        contentPane.add(Space);
        contentPane.add(SpaceUser);
        contentPane.add(SpaceScore);
        contentPane.add(Snake);
        contentPane.add(SnakeUser);
        contentPane.add(SnakeScore);
        contentPane.add(BS);
        contentPane.add(BSUser);
        contentPane.add(BSScore);
        contentPane.add(Slot);
        contentPane.add(SlotUser);
        contentPane.add(SlotScore);
        contentPane.add(Troll);
        contentPane.add(TrollUser);
        contentPane.add(TrollScore);
        contentPane.add(Frogger);
        contentPane.add(FroggerUser);
        contentPane.add(FroggerScore);
        contentPane.add(User);
        contentPane.add(Score);
        contentPane.add(Brick);
        contentPane.add(PinBall);
        contentPane.add(Trapped);
        contentPane.add(BrickScore);
        contentPane.add(BrickUser);
        contentPane.add(PinBallScore);
        contentPane.add(PinBallUser);
        contentPane.add(TrappedScore);
        contentPane.add(TrappedUser);
        contentPane.add(exit);
        getContentPane().add(contentPane);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        pack();
        setVisible(true);
    }
    private void exit (ActionEvent evt) 
    {
        this.dispose();
    }
    public static void currentUser(String u)
    {
        currentUser = u;
    }
    public static String getUser()
    {
        return currentUser;
    }
    public static void setUser(String s)
    {
        currentUser = s;
    }
    public static void main(String[] args) throws IOException{
        //System.setProperty("swing.defaultlaf", "com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
        //javax.swing.SwingUtilities.invokeLater(new Runnable() {
            //public void run() {

                    new HighScores();
            //}
        //});
    }
}
